laravel/app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('empresa', 'EmpresaController@index')->name('empresa');
    Route::get('produtos/{categoria_slug?}', 'ProdutosController@index')->name('produtos');
    Route::get('catalogo/{id}', 'ProdutosController@catalogo')->name('catalogo');
    Route::post('catalogo', 'ProdutosController@catalogoPost')->name('catalogo.post');
    Route::get('orcamento', 'OrcamentoController@index')->name('orcamento');
    Route::post('orcamento', 'OrcamentoController@post')->name('orcamento.post');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
        Route::get('produtos/delete-catalogo/{produtos_id}', 'ProdutosController@deleteCatalogo')->name('painel.produtos.deleteCatalogo');
		Route::resource('produtos', 'ProdutosController');
        Route::resource('produtos.imagens', 'ProdutosImagensController');
		Route::resource('empresa', 'EmpresaController', ['only' => ['index', 'update']]);
		Route::resource('chamadas', 'ChamadasController');
		Route::resource('banners', 'BannersController');

        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::get('orcamentos/{orcamentos}/toggle', ['as' => 'painel.orcamentos.toggle', 'uses' => 'OrcamentosController@toggle']);
        Route::resource('orcamentos', 'OrcamentosController');
        Route::resource('usuarios', 'UsuariosController');

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\BannersRequest;
use App\Http\Controllers\Controller;

use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $registros = Banner::ordenados()->get();

        return view('painel.banners.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Banner $registro)
    {
        return view('painel.banners.edit', compact('registro'));
    }

    public function update(BannersRequest $request, Banner $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Banner $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ChamadasController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ChamadasRequest;
use App\Http\Controllers\Controller;

use App\Models\Chamada;

class ChamadasController extends Controller
{
    public function index()
    {
        $registros = Chamada::ordenados()->get();

        return view('painel.chamadas.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.chamadas.create');
    }

    public function store(ChamadasRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Chamada::upload_imagem();

            Chamada::create($input);

            return redirect()->route('painel.chamadas.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Chamada $registro)
    {
        return view('painel.chamadas.edit', compact('registro'));
    }

    public function update(ChamadasRequest $request, Chamada $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Chamada::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.chamadas.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Chamada $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.chamadas.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('created_at', 'DESC')->get();

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }

    public function toggle(ContatoRecebido $contato, Request $request)
    {
        try {

            $contato->update([
                'lido' => !$contato->lido
            ]);

            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/EmpresaController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\EmpresaRequest;
use App\Http\Controllers\Controller;

use App\Models\Empresa;

class EmpresaController extends Controller
{
    public function index()
    {
        $registro = Empresa::first();

        return view('painel.empresa.edit', compact('registro'));
    }

    public function update(EmpresaRequest $request, Empresa $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_1'])) $input['imagem_1'] = Empresa::upload_imagem_1();
            if (isset($input['imagem_2'])) $input['imagem_2'] = Empresa::upload_imagem_2();
            if (isset($input['imagem_3'])) $input['imagem_3'] = Empresa::upload_imagem_3();
            if (isset($input['imagem_4'])) $input['imagem_4'] = Empresa::upload_imagem_4();

            $registro->update($input);

            return redirect()->route('painel.empresa.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/GeneratorController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Support\Facades\Artisan;

class GeneratorController extends Controller
{
    public function index()
    {
        return view('painel.generator.index');
    }

    public function submit(Request $request)
    {
        $this->validate($request, [
            'type'         => 'required',
            'resourceName' => 'required',
            'unitName'     => 'required_if:type,default'
        ]);

        $type = $request->get('type');

        $parameters = [
            'resourceName' => $request->get('resourceName'),
            'fields'       => $request->get('fields'),
        ];

        if(!empty($request->get('campos_nome')[0])) {
            $fields = '';
            foreach ($request->get('campos_nome') as $key => $campo_nome) {
                $field = [
                    $campo_nome,
                    $request->get('campos_tipo')[$key],
                    $request->get('campos_validation')[$key]
                ];

                $field = implode(':', $field);

                if (array_key_exists($key+1, $request->get('campos_nome'))) {
                    $fields .= $field.',';
                } else {
                    $fields .= $field;
                }
            }

            if (!empty($request->get('fields'))) {
                $parameters['fields'] = $request->get('fields').','.$fields;
            } else {
                $parameters['fields'] = $fields;
            }
        }

        if ($type == 'default') {
            $parameters['unitName'] = $request->get('unitName');
            $parameters['--slug']   = $request->get('slug');

            if ($request->get('paginate')) {
                $parameters['--paginate'] = $request->get('paginate');
            }
            if ($request->get('sortable')) {
                $parameters['--sortable'] = true;
            }
            if ($request->get('gallery')) {
                $parameters['--gallery'] = true;
            }
            if ($request->get('categories')) {
                $parameters['--categories'] = true;
            }
            if ($request->get('tags')) {
                $parameters['--tags'] = true;
            }
        }

        if ($request->get('force')) {
            $parameters['--force'] = true;
        }

        try {

            Artisan::call('resource:'.$type, $parameters);
            $output = Artisan::output();

            return back()->with(compact('output'))->withInput();

        } catch (\Exception $e) {

            return back()->withErrors([$e->getMessage()])->withInput();

        }

    }
}

laravel/app/Http/Controllers/Painel/OrcamentosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\Orcamento;

class OrcamentosController extends Controller
{
    public function index()
    {
        $orcamentos = Orcamento::orderBy('created_at', 'DESC')->get();

        return view('painel.orcamentos.index', compact('orcamentos'));
    }

    public function show(Orcamento $orcamento)
    {
        $orcamento->update(['lido' => 1]);

        return view('painel.orcamentos.show', compact('orcamento'));
    }

    public function destroy(Orcamento $orcamento)
    {
        try {

            $orcamento->delete();
            return redirect()->route('painel.orcamentos.index')->with('success', 'Orçamento excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir orçamento: '.$e->getMessage()]);

        }
    }

    public function toggle(Orcamento $orcamento, Request $request)
    {
        try {

            $orcamento->update([
                'lido' => !$orcamento->lido
            ]);

            return redirect()->route('painel.orcamentos.index')->with('success', 'Orçamento alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar orçamento: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/PainelController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use DB;
use App\Helpers\CropImage;

class PainelController extends Controller
{

    public function index()
    {
        return view('painel.home');
    }

    public function order(Request $request)
    {
        if (!$request->ajax()) return false;

        $data  = $request->input('data');
        $table = $request->input('table');

        for ($i = 0; $i < count($data); $i++) {
            DB::table($table)->where('id', $data[$i])->update(array('ordem' => $i + 1));
        }

        return json_encode($data);
    }

    private $image_config = [
        'width'  => 980,
        'height' => null,
        'upsize' => true,
        'path'   => 'assets/img/editor/'
    ];

    public function imageUpload(Request $request)
    {
        $validator = \Validator::make($request->all(), [
            'imagem' => 'image|required'
        ]);

        if ($validator->fails()) {
            $response = [
                'error'   => true,
                'message' => 'O arquivo deve ser uma imagem.'
            ];
        } else {
            $imagem   = CropImage::make('imagem', $this->image_config);
            $response = [
                'filepath' => asset($this->image_config['path'] . $imagem)
            ];
        }

        return response()->json($response);
    }
}

laravel/app/Http/Controllers/ProdutosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Models\Categoria;
use App\Models\Contato;

class ProdutosController extends Controller
{
    public function index(Categoria $categoria)
    {
        if (!$categoria->exists) {
            $categoria = Categoria::ordenados()->first();
        }

        if (!$categoria) abort('404');

        $categorias = Categoria::ordenados()->get();

        return view('frontend.produtos', compact('categorias', 'categoria'));
    }

    public function catalogo($id)
    {
        $categoria = Categoria::findOrFail($id);
        if (!$categoria->catalogo) abort('404');

        return view('frontend.catalogo', compact('categoria'));
    }

    public function catalogoPost(Request $request)
    {
        $this->validate($request, [
            'id'       => 'required',
            'nome'     => 'required',
            'email'    => 'required|email',
            'telefone' => 'required'
        ]);

        $categoria = Categoria::findOrFail($request->get('id'));
        if (!$categoria->catalogo) abort('404');

        $input = $request->all();
        $input['catalogo'] = $categoria->catalogo_nome;

        $contato = Contato::first();

        if (isset($contato->email)) {
            \Mail::send('emails.catalogo', $input, function($message) use ($request, $contato)
            {
                $message->to($contato->email, config('site.name'))
                        ->subject('[CATÁLOGO] '.config('site.name'))
                        ->replyTo($request->get('email'), $request->get('nome'));
            });
        }

        return response()->json([
            'link' => url('assets/catalogos/'.$categoria->catalogo)
        ]);
    }
}

laravel/resources/views/painel/produtos/create.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Produtos /</small> Adicionar Categoria</h2>
    </legend>

    {!! Form::open(['route' => 'painel.produtos.store', 'files' => true]) !!}

        @include('painel.produtos.form', ['submitText' => 'Inserir'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/produtos/edit.blade.php
@extends('painel.common.template')

@section('content')

    <legend>
        <h2><small>Produtos /</small> Editar Categoria</h2>
    </legend>

    {!! Form::model($registro, [
        'route'  => ['painel.produtos.update', $registro->id],
        'method' => 'patch',
        'files'  => true])
    !!}

    @include('painel.produtos.form', ['submitText' => 'Alterar'])

    {!! Form::close() !!}

@endsection

laravel/resources/views/painel/produtos/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('titulo', 'Título') !!}
    {!! Form::text('titulo', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('linha', 'Linha') !!}
    {!! Form::text('linha', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('descricao', 'Descrição') !!}
    {!! Form::textarea('descricao', null, ['class' => 'form-control ckeditor', 'data-editor' => 'produtos']) !!}
</div>

<div class="well form-group">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                {!! Form::label('catalogo', 'Catálogo') !!}
                @if(isset($registro) && $registro->catalogo)
                <p>
                    <a href="{{ url('assets/catalogos/'.$registro->catalogo) }}" target="_blank" style="display:block;">{{ $registro->catalogo }}</a>
                    <a href="{{ route('painel.produtos.deleteCatalogo', $registro->id) }}" class="btn-delete btn-delete-link label label-danger">
                        <i class="glyphicon glyphicon-remove" style="margin-right:5px"></i>
                        REMOVER
                    </a>
                </p>
                @endif
                {!! Form::file('catalogo', ['class' => 'form-control']) !!}
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group" style="margin-bottom: 0">
                {!! Form::label('catalogo_nome', 'Nome do Catálogo') !!}
                {!! Form::text('catalogo_nome', null, ['class' => 'form-control']) !!}
            </div>
        </div>
    </div>
</div>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.produtos.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/produtos/index.blade.php
@extends('painel.common.template')

@section('content')

    @include('painel.common.flash')

    <legend>
        <h2>
            Produtos
            <a href="{{ route('painel.produtos.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Categoria</a>
        </h2>
    </legend>


    @if(!count($registros))
    <div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
    @else
    <table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="produtos">
        <thead>
            <tr>
                <th>Ordenar</th>
                <th>Título</th>
                <th>Imagens</th>
                <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)
            <tr class="tr-row" id="{{ $registro->id }}">
                <td>
                    <a href="#" class="btn btn-info btn-sm btn-move">
                        <span class="glyphicon glyphicon-move"></span>
                    </a>
                </td>
                <td>{{ $registro->titulo }}</td>
                <td>
                    <a href="{{ route('painel.produtos.imagens.index', $registro->id) }}" class="btn btn-info btn-sm">
                        <span class="glyphicon glyphicon-picture" style="margin-right:10px;"></span>Gerenciar
                    </a>
                </td>
                <td class="crud-actions">
                    {!! Form::open([
                        'route'  => ['painel.produtos.destroy', $registro->id],
                        'method' => 'delete'
                    ]) !!}

                    <div class="btn-group btn-group-sm">
                        <a href="{{ route('painel.produtos.edit', $registro->id ) }}" class="btn btn-primary btn-sm pull-left">
                            <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                        </a>

                        <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                    </div>

                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @endif

@endsection